version: '3.1'
services:
  chromadb:
    image: chromadb/chroma
    restart: always
    ports:
      - "8000:8000"
    container_name: chromadb

  chatollama:
    image: 0001coder/chatollama:latest
    pull_policy: always
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    volumes:
      - ~/.chatollama:/app/sqlite
